"""technical_drawings_for_agents — engineering-drawings-as-code toolkit.

Generic SVG drawing furniture (generalised from an earlier vessel-design ``svg_utils``), an
ezdxf DXF exporter, and a render/validate CLI. Projects import this toolkit;
they do not copy it.
"""

from __future__ import annotations

__version__ = "0.1.0"

from .style import (  # noqa: F401
    STATUS_ORDER,
    STATUS_WATERMARKS,
)
from .svg import (  # noqa: F401
    Drawing,
    HATCH_PATTERNS,
    ViewBox,
    svg_border,
    svg_centerline,
    svg_circle,
    svg_dimension_h,
    svg_dimension_v,
    svg_ellipse,
    svg_hatch,
    svg_leader,
    svg_line,
    svg_north_arrow,
    svg_path,
    svg_pattern_defs,
    svg_polygon,
    svg_provenance_stamp,
    svg_rect,
    svg_scale_bar,
    svg_status_watermark,
    svg_text,
    svg_title_block,
    svg_wrap,
)
from .meta import DrawingMeta  # noqa: F401
from .revisions import (  # noqa: F401
    PRE_REGISTER_SENTINEL,
    REV_SCHEMES,
    Revision,
    RevisionError,
    RevisionRegister,
)
from .numbering import (  # noqa: F401
    BUILTIN_SCHEMES,
    SHAPE_ONLY,
    NumberingError,
    NumberingScheme,
    Segment,
)
from .titleblock import (  # noqa: F401
    ISO7200_180MM,
    Cell,
    PaperFrame,
    TitleBlockError,
    TitleBlockFields,
    TitleBlockLayout,
    EXAMPLE_A3,
    assert_layout_fits,
    iso7200_title_block,
    revision_block,
    title_block_extents_mm,
)

# Paper-space sheets (millimetres). `Viewport` is exported as `SheetViewport` on
# purpose: sitting next to the pixel-space `ViewBox` under its own name it would invite
# exactly the px/mm unit confusion the two-assembler split exists to prevent. Import it
# as `technical_drawings_for_agents.sheet.Viewport` when you want the plain name.
from .sheet import (  # noqa: F401
    ISO_PREFERRED_DENOMINATORS,
    LW_DEFAULT_MM,
    PAPER_SIZES_MM,
    PREFERRED_DENOMINATORS,
    Margins,
    NorthRef,
    PaperSize,
    PlotScale,
    Reservation,
    ScaleBarSpec,
    Sheet,
    SheetDrawing,
    SheetError,
    SheetFrame,
    Viewport as SheetViewport,
    load_sheet_config,
    read_sheet_metadata,
    resolve_sheet,
    sheet_frame,
    sheet_metadata_json,
    sheet_north_arrow,
    sheet_scale_bar,
    sheet_title_block_placeholder,
    read_sheet_data_attr,
)
from .layers import (  # noqa: F401
    DEFAULT_PX_PER_MM,
    ApplyReport,
    LayerSpec,
    LayerTable,
    LayerTableError,
    LinetypeSpec,
    Pen,
    default_layer_table,
    load_layer_table,
    resolve_layer_table,
)
from .dxf import DxfBuilder  # noqa: F401
from .provenance import (  # noqa: F401
    EmitPolicy,
    Manifest,
    ProvenanceError,
    emit_digest,
    format_reproducibility,
    mask_dxf_volatiles,
    stamp_text,
)
from . import isa  # noqa: F401  (ISA-5.1 symbol library)
from .isa import Symbol, build_symbol  # noqa: F401
from .ingest import (  # noqa: F401
    apply_corrections,
    convert_dwg,
    crop_pdf,
    find_oda,
    improve,
    isolate_sheet,
    load_clean,
    normalise_text,
    recolor,
    strip_tags,
)

__all__ = [
    "__version__",
    "ViewBox",
    "Drawing",
    "HATCH_PATTERNS",
    "DrawingMeta",
    "Revision",
    "RevisionRegister",
    "RevisionError",
    "REV_SCHEMES",
    "PRE_REGISTER_SENTINEL",
    "NumberingScheme",
    "NumberingError",
    "Segment",
    "SHAPE_ONLY",
    "BUILTIN_SCHEMES",
    "PaperFrame",
    "TitleBlockFields",
    "TitleBlockLayout",
    "TitleBlockError",
    "Cell",
    "ISO7200_180MM",
    "EXAMPLE_A3",
    "assert_layout_fits",
    "iso7200_title_block",
    "revision_block",
    "title_block_extents_mm",
    "SheetError",
    "PAPER_SIZES_MM",
    "PREFERRED_DENOMINATORS",
    "ISO_PREFERRED_DENOMINATORS",
    "LW_DEFAULT_MM",
    "Margins",
    "PaperSize",
    "Reservation",
    "SheetFrame",
    "PlotScale",
    "SheetViewport",
    "Sheet",
    "NorthRef",
    "ScaleBarSpec",
    "SheetDrawing",
    "load_sheet_config",
    "resolve_sheet",
    "sheet_frame",
    "sheet_scale_bar",
    "sheet_north_arrow",
    "sheet_title_block_placeholder",
    "read_sheet_data_attr",
    "sheet_metadata_json",
    "read_sheet_metadata",
    "DEFAULT_PX_PER_MM",
    "ApplyReport",
    "LayerSpec",
    "LayerTable",
    "LayerTableError",
    "LinetypeSpec",
    "Pen",
    "load_layer_table",
    "default_layer_table",
    "resolve_layer_table",
    "DxfBuilder",
    "EmitPolicy",
    "Manifest",
    "ProvenanceError",
    "emit_digest",
    "format_reproducibility",
    "mask_dxf_volatiles",
    "stamp_text",
    "isa",
    "Symbol",
    "build_symbol",
    "STATUS_ORDER",
    "STATUS_WATERMARKS",
    "convert_dwg",
    "load_clean",
    "improve",
    "strip_tags",
    "isolate_sheet",
    "apply_corrections",
    "crop_pdf",
    "recolor",
    "normalise_text",
    "find_oda",
    "svg_line",
    "svg_rect",
    "svg_circle",
    "svg_ellipse",
    "svg_polygon",
    "svg_provenance_stamp",
    "svg_path",
    "svg_text",
    "svg_border",
    "svg_centerline",
    "svg_dimension_h",
    "svg_dimension_v",
    "svg_hatch",
    "svg_leader",
    "svg_north_arrow",
    "svg_pattern_defs",
    "svg_scale_bar",
    "svg_status_watermark",
    "svg_title_block",
    "svg_wrap",
]
