"""Parametric, to-scale component geometry.

Component specs describe project-agnostic equipment geometry in real metres.
Placement maps that local geometry into drawing or GIS coordinates; emitters
then write GeoJSON, SVG, or DXF without reinterpreting the source YAML.
"""

from __future__ import annotations

from .dimensions import (
    AnnotationBox,
    Chain,
    Datum,
    DimensionError,
    DimensionSet,
    DimensionSpec,
    Measurement,
    Ref,
    Route,
    SettingOutRow,
    SettingOutSpec,
    SettingOutTable,
    Style,
    chain_tolerance_mm,
    check_chains,
    check_dimensions,
    displayed_value,
    dump_measurements,
    dump_setting_out,
    effective_layout,
    format_value,
    load_dimensions,
    measure,
    placement_key,
    project_onto_route,
    render_dimensions,
    resolve,
    setting_out_rows,
    setting_out_table,
)
from .emit import to_dxf, to_geojson, to_svg
from .layout import (
    REGISTER_ROUND_DP,
    Check,
    Finding,
    Group,
    Layout,
    LayoutError,
    Placement,
    RegisterDrift,
    build_layout,
    canonical_instances,
    canonical_sort_key,
    canonicalise_register,
    check_layout,
    check_register,
    derive_placements,
    dump_placements_register,
    footprint,
    footprint_pose,
    id_coverage,
    load_layout,
    placement_instance,
    polygon_gap,
    snap_groups,
)
from .place import PlacedFeature, place
from .spec import (
    Component,
    ComponentInfo,
    ComponentSpecError,
    Feature,
    FromDxf,
    Shape,
    load_component,
)

__all__ = [
    "REGISTER_ROUND_DP",
    "AnnotationBox",
    "Chain",
    "Check",
    "Component",
    "ComponentInfo",
    "ComponentSpecError",
    "Datum",
    "DimensionError",
    "DimensionSet",
    "DimensionSpec",
    "Feature",
    "Finding",
    "FromDxf",
    "Group",
    "Layout",
    "LayoutError",
    "Measurement",
    "PlacedFeature",
    "Placement",
    "Ref",
    "RegisterDrift",
    "Route",
    "SettingOutRow",
    "SettingOutSpec",
    "SettingOutTable",
    "Shape",
    "Style",
    "build_layout",
    "canonical_instances",
    "canonical_sort_key",
    "canonicalise_register",
    "chain_tolerance_mm",
    "check_chains",
    "check_dimensions",
    "check_layout",
    "check_register",
    "derive_placements",
    "displayed_value",
    "dump_measurements",
    "dump_placements_register",
    "dump_setting_out",
    "effective_layout",
    "footprint",
    "footprint_pose",
    "format_value",
    "id_coverage",
    "load_component",
    "load_dimensions",
    "load_layout",
    "measure",
    "place",
    "placement_instance",
    "placement_key",
    "polygon_gap",
    "project_onto_route",
    "render_dimensions",
    "resolve",
    "setting_out_rows",
    "setting_out_table",
    "snap_groups",
    "to_dxf",
    "to_geojson",
    "to_svg",
]
